### ISSUE TITLE
[3 Monthly Report Data] Questionnaire for Mobile Telephony Service

### ISSUE THREAD

**Issue by blertath** [opendatakosovo/arkep#182]
**Description**
As a client already Authorized by the ARKEP Authority I want to be able to view data of the  Questionnaire for Mobile Telephony Service, for my 3 monthly report.

**Acceptance Criteria**
[ ] View Reports of the Questionnaire for Mobile Telephony Service

**Comment by arianithetemi** [comment]
I see that in this report view are some data missing, you can repro by sending a new report of this kind and go to View of this report, check with attention the sections: PËRDORUESIT DHE NDARJA E TYRE, PËRDORUESIT ME QASJE NË INTERNET, PËRDORUESIT ME QASJE VETËM NË INTERNET (DATA SIM) and some other fileds. You can't see the actual data submitted in this sections!
