### ISSUE TITLE
[ADMIN SIDE] Instantly Update and Delete 

### ISSUE THREAD

**Issue by blertath** [opendatakosovo/arkep#185]
**Description**
As an ADMIN Person from the ARKEP Authority when I approve or cancel a request for changes, I want to be able to instantly see the updated list with the status of the request.

**Acceptance Criteria**
- [x] Instantly Update the status of request for changes 
- [x] Instantly Delete Services in the Company Profile

**Comment by blertath** [comment]
@arianithetemi when trying to save the changes when I edited in the company profile, it takes a lot of time to save them. Can you please check again, it was working fine before we added the instant feature. Thank you!

**Comment by arianithetemi** [comment]
I just checked and it worked fine! Can you please test again and if you can repro this bug, please write me down the steps of repro this bug in order to have more easier to repro and see the bug happening. Thanks
